### ISSUE TITLE
FAQ Command(s)

### ISSUE THREAD

**Issue by mervynfoxe** [AMVPh34r/discord-willy#1]
One or multiple commands for answering general FAQ-type questions. e.g. list of dailies, trade fee, etc

**Comment by BlackSapphire** [comment]
Hey! I think it'd be cool along with the other FAQ type stuff, you could include asking Willy about the Site Rules and the Discord rules.

**Comment by MauitheGoblinKing** [comment]
A command to check Digis time and active events/their end dates might be helpful

**Comment by mervynfoxe** [comment]
Definitely a good idea, though probably not the best for a subset of the `!faq` command. If you want to open a new issue with this suggestion feel free!

**Comment by mervynfoxe** [comment]
Implemented in commit 3258dce
