### ISSUE TITLE
Idea: List of Various Staff Members+Types

### ISSUE THREAD

**Issue by BlackSapphire** [AMVPh34r/discord-willy#2]
Have him spit out a list of X type of staff members when you ask?
Pretty much just an excuse for more Willy speech/flavor. But I think it'd be cute to have him referring to the Mods as cops/sheriffs or something |D

**Comment by mervynfoxe** [comment]
Turns out this isn't really easily doable with the current site codebase. For now you can run `!faq staff` to get a link to the staff page but there's no good way to have the bot himself list staff members. I can revisit this after the recode is finished and we have a more robust API.
