### ISSUE TITLE
Idea: How Many

### ISSUE THREAD

**Issue by BlackSapphire** [AMVPh34r/discord-willy#3]
It'd be cool if either included in the Item Info or another lookup you could do would be the "How Many on Site" feature.

**Comment by AMVPh34r** [comment]
Do you mean something like how many of a specific item exist across all users' backpacks? Or how many items of a specific type exist on the site (e.g. how many scarves are there)?

**Comment by BlackSapphire** [comment]
I was meaning across the site itself. I was thinking that it'd just pull the info from here: http://yaydigis.net/p_help_search_count.php

**Comment by mervynfoxe** [comment]
Implemented in commit ced724d
