### ISSUE TITLE
Idea: Shop Switches n stuff

### ISSUE THREAD

**Issue by BlackSapphire** [AMVPh34r/discord-willy#8]
-Current FotM+When next Switch.
-When the next Seasonal Switch is supposed to happen.

**Comment by mervynfoxe** [comment]
FotM is planned, seasonals may or may not be doable, will look into it.

**Comment by mervynfoxe** [comment]
Implemented in commit 773d171.
Seasonals unfortunately isn't really viable currently, with the way they're handled through the site. This can be revisited after the site recode.
