### ISSUE TITLE
Discord Willy: Helpful Answers

### ISSUE THREAD

**Issue by MauitheGoblinKing** [AMVPh34r/discord-willy#9]
My main two ideas are the current Digis time, and which current events are active and their end dates. (also possibly who is running them so users know who to contact with questions)
The FoTM could also be useful, I think, especially if it could bring up a picture, but I'm not sure how doable that would be.

**Comment by mervynfoxe** [comment]
Time is super simple to take care of, FotM should be doable and I'll have to look into events, that one entirely hinges on how the site handles them.

**Comment by mervynfoxe** [comment]
Implemented in commit 773d171.
Added `!time` and `!fotm`. Unfortunately events can't really be done with the current codebase. This can be revisited after the site recode.
